# Generated by Django 3.1.3 on 2022-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0002_auto_20220813_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Cliente'),
        ),
    ]
